# Generated by Django 5.1.6 on 2025-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binance_Data',
            fields=[
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'binancedata',
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timestamp'), name='unique_Binance_Data_symbol_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'HistoryData',
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timestamp'), name='unique_historydata_symbol_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='IbApi_Data',
            fields=[
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'IbApi_Data',
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timestamp'), name='unique_IbApi_Data_symbol_timestamp')],
            },
        ),
    ]
